apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - image: quay.io/praveenrachamreddy/ci-pipeline:1.1-SNAPSHOT-dev
          imagePullPolicy: Always
          name: webapp
          ports:
            - containerPort: 8080
              protocol: TCP

