resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:5799a8a7f4c17afe0b722e14a22178d7d0f641349e95fa1cf87dcf0b26216b06
  name: quay.io/praveenrachamreddy/ci-pipeline
  newName: quay.io/praveenrachamreddy/ci-pipeline:1.1-SNAPSHOT-dev
