resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:e7a76354de4f2b9cdd11d3f82c47d395797b22dfc63184041fd83cab4049ed03
  name: quay.io/praveenrachamreddy/ci-pipeline
  newName: quay.io/praveenrachamreddy/ci-pipeline:1.1-SNAPSHOT-dev
