resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:f54f23a14ecf3202866595f5475c46bf06d64def80b5fa81b48ab85a1032e250
  name: quay.io/praveenrachamreddy/ci-pipeline
  newName: quay.io/praveenrachamreddy/ci-pipeline:6312c0ba64cfc7b0fd14e08a709ae0c905188838
