resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:918d838bffd6d3e7a8eb73fa6c38eb47eb892fd89bdc0957923068ba90152d91
  name: quay.io/praveenrachamreddy/ci-pipeline
  newName: quay.io/praveenrachamreddy/ci-pipeline:1.1-SNAPSHOT-dev
