apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:f3fcfc5b3660ad3e851ca490b6710774f20c6926c02213def55765c958f99216
  name: quay.io/praveenrachamreddy/ci-pipeline
  newName: quay.io/praveenrachamreddy/ci-pipeline
- digest: sha256:ca04e06864db1ea964b5fa7f6e59b0659b3466615dd31783b54e695c66a8d50a
  name: quay.io/praveenrachamreddy/ci-pipeline1:1.0--DEV
  newName: quay.io/praveenrachamreddy/ci-pipeline1:1.0-DEV
