apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- digest: sha256:f3fcfc5b3660ad3e851ca490b6710774f20c6926c02213def55765c958f99216
  name: quay.io/praveenrachamreddy/ci-pipeline
  newName: quay.io/praveenrachamreddy/ci-pipeline
- digest: sha256:029dc556a1945e71c2b8e286e10ebdc3d38ca12c579c7af4df0bd85b306ce064
  name: quay.io/praveenrachamreddy/ci-pipeline1:1.0--DEV
  newName: quay.io/praveenrachamreddy/ci-pipeline1:1.0-DEV
